---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: ((haproxy-backend-port))
        backend_servers: ((haproxy-backend-servers))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

releases:
- name: bpm
  version: 1.1.19
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.19
  sha1: 669baca975c6def518c7e736dbf189cfb438475b
- name: haproxy
  version: 11.16.4+2.6.9
  url: https://github.com/b1tamara/haproxy-boshrelease/releases/download/v11.16.4+2.6.9/haproxy-11.16.4+2.6.9.tgz
  sha1: 3b8825b90fa444a060346f191a5ddc6fc91ffe33
